experiment_name: "all_hyperparameters"

experiment_file:
  - "750332458"
  - "750749662"
  - "754312389"
  - "all"

i_dataset:
  - "static_gratings_params"
  - "static_gratings_images"
  - "natural_images"
  - "static_and_natural_images"

orientations:
  - [0, 90]
  - [0, 30, 60, 90, 120, 150]
  - null

units:
  - "VISp"
  - null

# For the j_dataset (any value)
num_bins:
  - 25
  - 50
  - 100
  - 200

# For the j_dataset ("all" or any value)
num_neurons:
  - 25
  - 50
  - 100
  - "all"

# For the j_dataset
neuron_selection:
  - "variance"
  - "class_variance"

dimensionality_reduction:
  - "autoencoder"
  - "pca"
  - "truncatedsvd"
  - "nmf"

# Associated with dimensionality_reduction
reduced_dimension:
  - 10
  - 20
  - 32
  - 64

standardize_post_reduction:
  - True
  - False

density_estimator:
  - "nadaraya_watson"

# Any value
bandwidth_i:
  - "default"
  - 1

# Any value
bandwidth_j:
  - "default"
  - 1

density_to_log:
  - True
  - False

clustering:
  - "dirichlet_process_gaussian_mixture"

simplify_clustering:
  - True
  - False

# Any value
num_clusters:
  - 10
  - 20
  - 40
  - 80