experiment_name: "baseline_all_most_expressive_v1"

experiment_file: "750332458"

i_dataset: "static_gratings_params"

orientations: null

units: null

# For the j_dataset (any value)
num_bins: 100

# For the j_dataset ("all" or any value)
num_neurons: 100

# For the j_dataset
neuron_selection: "class_variance"

dimensionality_reduction: "pca"

reduced_dimension: 32

standardize_post_reduction: True

density_estimator: "nadaraya_watson"

bandwidth_i: "default"

bandwidth_j: "default"

density_to_log: False

clustering: "dirichlet_process_gaussian_mixture"

simplify_clustering: False

# Any value
num_clusters: 20